variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger: none
# pr trigger must not be excluded, but in the UI for the pipeline definition a setting has to be made.
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers
# for further info.

schedules:
  - cron: "15 4 * * *"  # 04:15 each day
    displayName: "Daily build"
    branches:
      include:
        - master

resources:
  containers:
    - container: dotnet-sdk-gnuplot5
      image: ghcr.io/gfoidl/datacompression/dotnet-gnuplot5

stages:
  - stage: Demos
    jobs:
      - template: jobs/demos.yml
