variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

# We don't need a CI trigger here, as the pipeline trigger starts this pipeline for master anyway.
trigger: none

resources:
  pipelines:
    - pipeline: ci-build
      source: DataCompression
      trigger:
        branches:
          include:
            - master

stages:
  - stage: Build_Docs
    jobs:
      - template: jobs/build_docs.yml

  - stage: Deploy
    dependsOn:
      - Build_Docs
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_docs.yml
