variables:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger:
  - master
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: Build_Test
    jobs:
      - template: jobs/build_and_test.yml
        parameters:
          # Need for tests .NET Framework 4.8
          name: windows
          vmImage: 'windows-2022'

  - stage: Code_Coverage
    dependsOn:
      - Build_Test
    jobs:
      - template: jobs/coverage.yml

  - stage: Deploy
    dependsOn:
      - Build_Test
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_nuget.yml
