jobs:
  - job: benchmarks
    pool:
      vmImage: ubuntu-20.04
    steps:
      # ~SDKs already installed~
      - template: steps/dotnet-install.yml

      - bash: |
          cd perf/gfoidl.DataCompression.Benchmarks
          dotnet restore
          dotnet build -c Release --no-restore
        displayName: build

      - bash: |
          cd perf
          chmod +x run-benchmarks.sh
          ./run-benchmarks.sh
        displayName: run benchmarks

      - publish: perf/gfoidl.DataCompression.Benchmarks/BenchmarkDotNet.Artifacts/results
        artifact: bench-results
        displayName: publish benchmark results
