jobs:
  - job: demos
    pool:
      vmImage: ubuntu-20.04
    container: dotnet-sdk-gnuplot5
    variables:
      SKIP_PLOT_DISPLAY: true
    steps:
      - bash: |
          cd demos
          dotnet restore
          dotnet build --no-restore
        displayName: build

      - bash: |
          cd demos
          chmod +x run.sh
          ./run.sh
        displayName: run demos

      - publish: demos/*/**/*.png
        artifact: plots
        displayName: publish plots
