jobs:
  - job: deploy_docs
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      GH_USER: gfoidl
      GH_EMAIL: $(GITHUB_EMAIL)
    steps:
      - checkout: self
        persistCredentials: true

      - bash: |
          git config user.name $GH_USER
          git config user.email $GH_EMAIL
        displayName: '[git] Configure User'

      - bash: git checkout gh-pages
        displayName: '[git] Set development branch'

      - bash: git rm -rf .
        displayName: '[git] Clean working dir'

      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'docs'
          targetPath: './'

      - bash: |
          git add --all
          git commit -m "Pipelines-Bot: Updated site via $(Build.SourceVersion)"
          echo ""
          git log --oneline
        displayName: '[git] Creating commit'

      - bash: 'git push origin gh-pages'
        displayName: '[git] Push changes to remote'
